name: CI

on: 
  push:
    branches:
      - master
    
jobs:
  my_first_act:
    runs-on:  ubuntu-latest
    
    steps: 
    - name: step1
      run: echo "Hey, that's first ACTION!!!!!"
      
    - name: copy-repo
      uses: actions/checkout@v3
    
    - name: Access cloned repository content
      run: |
        echo "DIRECTORY:"
        ls -la
    - name: run-tests
      run: pytest test_main.py 
